### ISSUE TITLE
Use DateTimeOriginal for timestamp

### ISSUE THREAD

**Issue by pseudobeer** [tomotetra/instagen#5]
https://github.com/tomotetra/instagen/blob/6abe6a6bc45c2d407179f47582d3d370f695434f/cmd/instagen/exif.go#L45

It would probably be better to use `DateTimeOriginal` field instead of `DateTime` for timestamp retrieval. When images are edited/developed, `DateTime` is updated and `DateTimeOriginal` is not.

It may depend on whether user wants to have original date, so we may also provide an option to choose between these two.

**Comment by tomotetra** [comment]
Thank you for your suggestion!
Fixed in  https://github.com/tomotetra/instagen/commit/9a7a7f79cd362c00392c78bd6ecfec253021cfc6
