### ISSUE TITLE
Makefile lacks go build

### ISSUE THREAD

**Issue by pseudobeer** [tomotetra/instagen#6]
https://github.com/tomotetra/instagen/blob/6abe6a6bc45c2d407179f47582d3d370f695434f/Makefile#L3

After this step, we should do something like:
```
go build
mv instagen /usr/local/bin/
```

Additionally, `make setup` should probably be `make install`.

**Comment by tomotetra** [comment]
Thank you for your suggestion!
Fixed in  https://github.com/tomotetra/instagen/commit/020aed6770c0016713a5cce2ffa8ef0a1a5d09ba
